services:
  solidify.api:
    image: ${DOCKER_REGISTRY-}solidifyapi
    build:
      context: .
      dockerfile: Solidify.API/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"

  solidify.cache:
    image: redis:latest
    restart: always
    ports:
       - '6379:6379'
